parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(function(){return l}):n&&(this[n]=l)}if(parcelRequire=f,i)throw i;return f}({"fcMS":[function(require,module,exports) {
function n(n,o){if(!(n instanceof o))throw new TypeError("Cannot call a class as a function")}module.exports=n;
},{}],"P8NW":[function(require,module,exports) {
function e(e,r){for(var n=0;n<r.length;n++){var t=r[n];t.enumerable=t.enumerable||!1,t.configurable=!0,"value"in t&&(t.writable=!0),Object.defineProperty(e,t.key,t)}}function r(r,n,t){return n&&e(r.prototype,n),t&&e(r,t),r}module.exports=r;
},{}],"Iwt6":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.component=void 0;var e=o(require("@babel/runtime/helpers/classCallCheck"));function o(e){return e&&e.__esModule?e:{default:e}}var r=function o(){(0,e.default)(this,o)},l={name:"hello-world",config:{bindings:{parentCtrl:"<"},controller:r,template:"<h1>Hello World</h1>"},enabled:!0,appendTo:"prm-top-bar-bedore",enableInView:".*"};exports.component=l;
},{"@babel/runtime/helpers/classCallCheck":"fcMS"}],"cGmI":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=a(require("@babel/runtime/helpers/classCallCheck")),n=a(require("@babel/runtime/helpers/createClass")),t=r(require("./components/helloWorld"));function o(){if("function"!=typeof WeakMap)return null;var e=new WeakMap;return o=function(){return e},e}function r(e){if(e&&e.__esModule)return e;if(null===e||"object"!=typeof e&&"function"!=typeof e)return{default:e};var n=o();if(n&&n.has(e))return n.get(e);var t={},r=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var a in e)if(Object.prototype.hasOwnProperty.call(e,a)){var i=r?Object.getOwnPropertyDescriptor(e,a):null;i&&(i.get||i.set)?Object.defineProperty(t,a,i):t[a]=e[a]}return t.default=e,n&&n.set(e,t),t}function a(e){return e&&e.__esModule?e:{default:e}}var i={};i.helloWorld=t,String.prototype.toCamelCase=function(){return this.split("-").map(function(e,n,t){return n>0?e.charAt(0).toUpperCase()+e.slice(1):e}).join("")};var c=function(){function t(){(0,e.default)(this,t)}return(0,n.default)(t,[{key:"load",value:function(e){this._injectComponentPlaceHoldersIntoAfterComponents(e)}},{key:"_importComponents",value:function(){var e=[];return Object.keys(Components).forEach(function(n){e.push(Components[n].component)}),e.filter(function(e){return e.enabled&&new RegExp(e.enableInView).test(window.appConfig.vid)})}},{key:"_createComponents",value:function(e){var n=this._importComponents(),t={};return console.log("Loading components"),n.forEach(function(n){if(console.log(n.name),n.enabled){if(n.appendTo){var o=t[n.appendTo]||[];o.push({name:n.name,enableInView:n.enableInView}),t[n.appendTo]=o}e.constant("afterComponents",t),e.component(n.name.toCamelCase(),n.config)}}),t}},{key:"_injectComponentPlaceHoldersIntoAfterComponents",value:function(e){var n=this._createComponents(e);Object.keys(n).forEach(function(t,o){var r=n[t];e.component(t.toCamelCase(),{bindings:{parentCtrl:"<"},template:r.map(function(e){return"<".concat(e.name,' parent-ctrl="$ctrl"></').concat(e.name,">")}).join("")})})}}]),t}();exports.default=c;
},{"@babel/runtime/helpers/classCallCheck":"fcMS","@babel/runtime/helpers/createClass":"P8NW","./components/helloWorld":"Iwt6"}],"Focm":[function(require,module,exports) {
"use strict";var u=a(require("./loader"));function a(u){return u&&u.__esModule?u:{default:u}}var e=new u.default,n=angualar.module("centralCustom",["angularLoad"]).run(function(u,a,e){console.log("in run")});e.load(n);
},{"./loader":"cGmI"}]},{},["Focm"], null)
//# sourceMappingURL=/custom.js.map